### ISSUE TITLE
API NOTPASS JOB 0 

### ISSUE THREAD

**Issue by lijiang2014** [JiangLiNSCC/eHPC#18]
JOB 0 的最后一个测试，一般情况下会通过，但有时会出现： 
```
PASS

jump to async
B2
{"status": "STARTED", "status_code": 100, "error": "Command running on task worker : {'hostname': 'celery@ln2', 'pid': 41430} ", "output": "ac7d4b4e-d1bb-4548-a990-295a290ec0ee"}
0


Traceback (most recent call last):
  File "main-test-sysu.py", line 330, in <module>
    eachtest()
  File "main-test-sysu.py", line 227, in test_post_command_machine
    if mc.ret200() and mc.data["output"]["retcode"] !=0  : print_PASS()
TypeError: string indices must be integers, not str
[tonge@tongeUbKy%tests]$python main-test-sysu.py job 0 
```

**Comment by lijiang2014** [comment]
修改 
```
if mc.ret200() and  mc.data["output"]["retcode"] !=0   : print_PASS()
```
为
```
if mc.ret200() and  (int( mc.data["output"]["retcode"] )!=0 )  : print_PASS()
```
现在基本可以通过，奇怪的错误。。。而且感觉测试程序没有等到异步结果成功就返回了。

**Comment by lijiang2014** [comment]
在后面还遇到一个类似的错误 ： 
```

jump to async
Traceback (most recent call last):
  File "main-test-sysu.py", line 330, in <module>
    eachtest()
  File "main-test-sysu.py", line 259, in test_get_job_machine
    myjobid = mc.data["output"]["jobid"]
TypeError: string indices must be integers, not str
[tonge@tongeUbKy%tests]$python main-test-sysu.py job 2

```

**Comment by lijiang2014** [comment]
跟踪发现，内部有些数据获取有额外的字符 ： 
```
('exe : ', TypeError('string indices must be integers, not str',))
('rdata : ', 'B2\r\n{"status": "STARTED", "status_code": 100, "error": "Command running on task worker : {\'hostname\': \'celery@ln2\', \'pid\': 41444} ", "output": "31d64d12-cd12-4e31-b3ea-cfbcaeeae545"}\r\n0\r\n\r\n')
Traceback (most recent call last):
  File "main-test-sysu.py", line 341, in <module>
    eachtest()
  File "main-test-sysu.py", line 267, in test_get_job_machine
    rep = mc.open("/job/" + machine_name + '/' , data = {"jobscript" : test_batchstr_long })
  File "main-test-sysu.py", line 95, in open
    return self.open( async_url + '/' + self.output )
  File "main-test-sysu.py", line 83, in open
    self.status_code = rdata["status_code"]
TypeError: string indices must be integers, not str
[tonge@tongeUbKy%tests]$

```

**Comment by lijiang2014** [comment]
```
        rdata = (rdata).decode('ascii')
        rdata_reg = re.search( '\{.+\}' ,rdata )
        rdata =  rdata if rdata_reg is None else rdata_reg.group()
        try :
            rdata =  json.loads(rdata)

```
目前采用对rdata 数据进行预处理的办法。
